### ISSUE TITLE
Infinite recursion of Ruby process spawning

### ISSUE THREAD

**Issue by jonleighton** [fedora-ruby/rubypick#10] opened 2015-02-15 21:24 UTC
I use @postmodern's [chruby](https://github.com/postmodern/chruby). I've just upgraded to Fedora 21. I found that using `/usr/bin/ruby` causes an infinite recursion of process spawning (when chruby is set to use a non-system ruby):

```
$ /usr/bin/ruby -e "omg"
^C/usr/share/rubygems/rubygems/ext/builder.rb:73:in ``': Interrupt
	from /usr/share/rubygems/rubygems/ext/builder.rb:73:in `run'
	from /usr/share/rubygems/rubygems/ext/ext_conf_builder.rb:38:in `block in build'
	from /usr/share/ruby/tempfile.rb:324:in `open'
	from /usr/share/rubygems/rubygems/ext/ext_conf_builder.rb:17:in `build'
	from /usr/share/rubygems/rubygems/ext/builder.rb:161:in `block (2 levels) in build_extension'
	from /usr/share/rubygems/rubygems/ext/builder.rb:160:in `chdir'
	from /usr/share/rubygems/rubygems/ext/builder.rb:160:in `block in build_extension'
	from /usr/share/rubygems/rubygems/ext/builder.rb:159:in `synchronize'
	from /usr/share/rubygems/rubygems/ext/builder.rb:159:in `build_extension'
	from /usr/share/rubygems/rubygems/ext/builder.rb:198:in `block in build_extensions'
	from /usr/share/rubygems/rubygems/ext/builder.rb:195:in `each'
	from /usr/share/rubygems/rubygems/ext/builder.rb:195:in `build_extensions'
	from /usr/share/rubygems/rubygems/specification.rb:1436:in `block in build_extensions'
	from /usr/share/rubygems/rubygems/user_interaction.rb:45:in `use_ui'
	from /usr/share/rubygems/rubygems/specification.rb:1434:in `build_extensions'
	from /usr/share/rubygems/rubygems/stub_specification.rb:60:in `build_extensions'
	from /usr/share/rubygems/rubygems/basic_specification.rb:56:in `contains_requirable_file?'
	from /usr/share/rubygems/rubygems/specification.rb:925:in `block in find_inactive_by_path'
	from /usr/share/rubygems/rubygems/specification.rb:924:in `each'
	from /usr/share/rubygems/rubygems/specification.rb:924:in `find'
	from /usr/share/rubygems/rubygems/specification.rb:924:in `find_inactive_by_path'
	from /usr/share/rubygems/rubygems.rb:185:in `try_activate'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:144:in `require'
	from <internal:abrt_prelude>:2:in `<compiled>'
```

Basically, from what I can tell, this is happening:

* Rubygems is trying to build some extension on startup (I'm not sure what/why but it may be something to do with abrt)
* It shells out to `/usr/bin/ruby extconf.rb`
* Which tries to build the extension... and so on

I think the problem may be happening because chruby has set up a bunch of environment variables:

```
$ env | egrep "GEM|RUBY"
GEM_HOME=/home/turnip/.gem/ruby/2.2.0
RUBY_ENGINE=ruby
GEM_ROOT=/home/turnip/.rubies/2.2.0/lib/ruby/gems/2.2.0
GEM_PATH=/home/turnip/.gem/ruby/2.2.0:/home/turnip/.rubies/2.2.0/lib/ruby/gems/2.2.0
RUBY_ROOT=/home/turnip/.rubies/2.2.0
RUBYOPT=
RUBY_VERSION=2.2.0
```

This is perhaps causing a conflict between the environment which `/usr/bin/ruby-mri` expects and the normal environment.

I tried adding the following before the `exec` in `/usr/bin/ruby`:

```
unset GEM_HOME RUBY_ENGINE GEM_ROOT GEM_PATH RUBY_ROOT RUBYOPT RUBY_VERSION
```

The infinite process spawning problem then went away.

Therefore I think this problem would be solved by setting those environment variables appropriately (or at least a subset of them).

**Comment by voxik** [comment] 2015-02-17 15:43
I am not user of chruby myself, but why chruby sets these variables? Moreover why the paths seems to point ro Ruby 2.2 locations? The issue is that the first thing RubyGems does when you ask to require anything (in this case it is the ```require 'abrt'``` by a chance, but it might be anything else), it tries to recompile the binary extensions of gems available in your GEM_PATH. Since these gems were build for Ruby 2.2, it tries to build them using system Ruby 2.1.

So to say, even if there were no rubypick, the behavior would be exactly the same.

**Comment by postmodern** [comment] 2015-02-17 20:46
chruby sets `GEM_HOME` and `GEM_PATH` to isolate gems on a per-ruby basis. chruby also sets `PATH` so that the ruby's `bin/` directory takes precedence. `RUBY_ROOT`, `RUBY_ENGINE` and `RUBY_VERSION` are common ruby switcher variables that chruby also sets, which one can use in their `PS1`.

**Comment by postmodern** [comment] 2015-02-17 20:52
This sounds more like a rubygems bug. By directly executing `/usr/bin/ruby`, it causes `Gem.ruby` to be `/usr/bin/ruby`. Thus rubygems sees an unfamiliar `GEM_HOME` and apparently starts recompiling C extensions on the fly.

**Comment by voxik** [comment] 2015-02-18 08:54
> chruby sets GEM_HOME and GEM_PATH to isolate gems on a per-ruby basis.

Yes, that is clear, however, you are trying to use system Ruby 2.1 with gems installed via Ruby 2.2. This simple can't work. It either fails with segfault or RubyGems are now trying to avoid the segfault by recompiling the binary extensions, which has different issues obviously.

> Are you sure it is really infinite, and not just taking a long time?

You said it is infinite loop and from my knowledge of RubyGems and their behavior, I can just confirm it ;)

I am closing this issue now, since I can't see anything related to rubypick. You would encounter similar behavior without it. Setting GEM_HOME and GEM_PATH has definitely its dark corners.

**Closed by voxik** 2015-02-18 08:54 UTC

**Comment by jonleighton** [comment] 2015-02-18 14:29
> Yes, that is clear, however, you are trying to use system Ruby 2.1 with gems installed via Ruby 2.2.

Yes, but not deliberately. (I fully agree that it cannot work.)

I guess I should have provided some more context in the original report... I bumped into this because after I upgraded, I tried to start vim. One of my vim plugins was invoking Ruby. For whatever reason it was invoking `/usr/bin/ruby` even though my Ruby 2.2 install had higher precedence in my `PATH`.

In the end I uninstalled the plugin as I determined I didn't need it. We could well conclude that the vim plugin is in fact the source of the bug...

But I guess I was thinking that maybe `/usr/bin/ruby` ought to work regardless of the state of the environment. For example if I install the `screenruler` package on Fedora, which depends on the system Ruby, one might say that it should be able to run regardless of the existence of `chruby` in my setup. I don't know if there are other situations where `/usr/bin/ruby` might be invoked even if I have a different ruby higher up in my `PATH`.

> Are you sure it is really infinite, and not just taking a long time?

I saw a tonne of processes being spawned very quickly, all the same. So yeah I'm pretty sure it's recursively spawning ruby processes.

> I am closing this issue now, since I can't see anything related to rubypick. You would encounter similar behavior without it. Setting GEM_HOME and GEM_PATH has definitely its dark corners.

I guess I'm thinking that if rubypick wanted to isolate the environment to the system gem locations, when `/usr/bin/ruby` is invoked, it could do so by setting these variables.

Do with this information what you like. I understand it's a complex intersection of different bits of software and it's pretty unclear what the behaviour "should" be or where the responsibility for the problem lies... it's not affecting me since I removed that vim plugin so I don't really care too much.

**Comment by voxik** [comment] 2015-02-18 21:41
> I guess I'm thinking that if rubypick wanted to isolate the environment to the system gem locations, when /usr/bin/ruby is invoked, it could do so by setting these variables.

This was never purpose of rubypick. Ruby pick should be transparent/invisible at the first place. It cannot change environment. Changing env variables would open whole new can of worms.
